title: "Jeremiah Isu"
author: "Jeremiah Isu"
description: "University of Oklahoma"
permalink: /:title/
lang: "en"
excerpt_separator: "\n\n\n"
date_format: "%B %d, %Y"

# Layout
show_excerpts: true
show_frame: false
show_sidebar: true
show_minimal: false

# Menu
navigation:
  - {file: "archive.html", title: "Home", icon: home}
  - {url: "assets/Jeremiah_Isu_CV.pdf", title: "CV", icon: user}

external:
  - {title: Mail, icon: envelope, url: "mailto:isujeremiah@ou.edu"}
  - {title: Github, icon: github, url: "https://github.com/isujeremiah?tab=repositories"}
  - {title: Linkedin, icon: linkedin, url: "https://linkedin.com"}

plugins:
  - jekyll-feed
